# Generated by Django 4.2.7 on 2023-11-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_alter_services_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
