# Generated by Django 4.2.7 on 2023-11-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_alter_services_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
